#ifndef _PLATFORM_CONFIG_DEFAULT_H_
#define _PLATFORM_CONFIG_DEFAULT_H_


#ifndef VL53L7CX_NB_TARGET_PER_ZONE
  #define   VL53L7CX_NB_TARGET_PER_ZONE   1U
#endif


// #define  VL53L7CX_USE_RAW_FORMAT


#define VL53L7CX_DISABLE_AMBIENT_PER_SPAD
#define VL53L7CX_DISABLE_NB_SPADS_ENABLED
#define VL53L7CX_DISABLE_NB_TARGET_DETECTED
#define VL53L7CX_DISABLE_SIGNAL_PER_SPAD
#define VL53L7CX_DISABLE_RANGE_SIGMA_MM
// #define VL53L7CX_DISABLE_DISTANCE_MM
#define VL53L7CX_DISABLE_REFLECTANCE_PERCENT
#define VL53L7CX_DISABLE_TARGET_STATUS
#define VL53L7CX_DISABLE_MOTION_INDICATOR

#endif  // _PLATFORM_CONFIG_DEFAULT_H_
