[env:body]
platform = ststm32
framework = arduino
board = genericSTM32F411RC
upload_speed = 115200
monitor_speed = 115200
upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=$UPLOAD_PORT br=115200 P=EVEN db=8 sb=1 dtr=high rts=low -w $SOURCE 0x08000000 -v -g
;extra_scripts = pre:scripts/flash_bridge.py
lib_deps = 
	arduino-libraries/Arduino_APDS9960@^1.0.4
	arduino-libraries/Arduino_MAX17332@^1.0.1
	stm32duino/STM32duino LSM6DSO@^2.2.0
	janelia-arduino/AT42QT@^0.7.2
	stm32duino/STM32duino MotionFX@^1.1.0
	gbr1/ucPack@^0.1.7
	stm32duino/STM32duino VL53L7CX@^1.0.3
lib_ignore = 
	STM32duino MotionFX
build_flags = 
	-I".pio/libdeps/body/STM32duino MotionFX/src"
	-L".pio/libdeps/body/STM32duino MotionFX/src/cortex-m4/fpv4-sp-d16-hard"
	-lMotionFX
build_src_filter = +<body>


[env:head]
platform = espressif32
framework = arduino
board = arduino_nano_esp32
upload_protocol = esptool
upload_speed = 115200
monitor_speed = 115200
lib_deps = 
	gbr1/ucPack@^0.1.7
build_src_filter = +<head>

[env:update_bridge]
platform = espressif32
framework = arduino
board = arduino_nano_esp32
upload_protocol = esptool
upload_speed = 115200
monitor_speed = 115200
lib_deps = 
	gbr1/ucPack@^0.1.7
build_src_filter = +<update_bridge>